/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_foolchen_ndkdemo_MainActivity */

#ifndef _Included_com_foolchen_ndkdemo_MainActivity
#define _Included_com_foolchen_ndkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_foolchen_ndkdemo_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_foolchen_ndkdemo_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_foolchen_ndkdemo_MainActivity
 * Method:    anotherString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_foolchen_ndkdemo_MainActivity_stringFromJNI2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
